### ISSUE TITLE
What's with these 5s and 15s?

### ISSUE THREAD

**Issue by Zyber17** [nulltitleexception/FellJS#4]
In game.js:

``` js
for (i = 0; i < entityNum; i++){
  var e = entities[i];
  context.fillStyle = e.color;
  drawImageMasked("player", e.color, gPIVX(e.x), gPIVY(e.y), e.width, e.height);
  context.fillText(e.name,(gPIVX(e.x) - (context.measureText(e.name).width / 2)) + 15,gPIVY(e.y) - 5);
}

context.fillText("Pos: (" + playerData.x + ", " + playerData.y + ")",5,15);
```

If they're important, you should assign a viable to equal them, so we can label those numbers.

**Comment by phi-fell** [comment]
ok, so the 15 in the upper part is completely separate from the lower one.
it should probably get a variable
the lower ones are just for the position of the debug position text in the window, and since that will be removed eventually, theres not much point in making it look nice so we have 3 lines to remove instead of one.

**Comment by phi-fell** [comment]
I forgot to mention, the upper 5 is also distinct and is the height difference between player image and name.

Also the upper 15 should probably be changed to (playerwidth / 2) or somesuch I think...  I forget why 15 was chosen but I think it was just "15 looks nice enough, on to the next thing"

**Comment by phi-fell** [comment]
I'll fix this stuff tomorrow cuz I'm tired.

**Comment by phi-fell** [comment]
ok, we're good.
